spring.application.name=practical
server.port=${PORT:8080}
logging.level.root=WARN
spring.datasource.url=jdbc:h2:mem:practical
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
